In [1]:
import tensorflow as tf
import numpy as np

In [8]:
max_features = 4
x = [
     [[0],[1],[1],[0],[0],[0]],
     [[0],[0],[0],[2],[2],[0]],
     [[0],[0],[0],[0],[3],[3]],
     [[0],[2],[2],[0],[0],[0]],
     [[0],[0],[3],[3],[0],[0]],
     [[0],[0],[0],[0],[1],[1]],
]

x = np.array(x, dtype=np.float32)
y = np.array([1,2,3,2,3,1], dtype=np.int32)

y2 = np.zeros((y.shape[0], max_features), dtype=np.float32)
y2[np.arange(y.shape[0]), y] = 1.0
print(y2)

model = tf.keras.Sequential([
  tf.keras.layers.LSTM(128, dropout=0.2, recurrent_dropout=0.2, input_dim=1),
  tf.keras.layers.Dense(4, activation='sigmoid')
])

model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

history = model.fit(x, y2, epochs=200)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]]
Epoch 1/200
1/1 [==============================] - 2s 2s/step - loss: 0.6960 - accuracy: 0.1667
Epoch 2/200
1/1 [==============================] - 0s 15ms/step - loss: 0.6870 - accuracy: 0.5000
Epoch 3/200
1/1 [==============================] - 0s 15ms/step - loss: 0.6816 - accuracy: 0.3333
Epoch 4/200
1/1 [==============================] - 0s 14ms/step - loss: 0.6713 - accuracy: 0.5000
Epoch 5/200
1/1 [==============================] - 0s 15ms/step - loss: 0.6648 - accuracy: 0.3333
Epoch 6/200
1/1 [==============================] - 0s 16ms/step - loss: 0.6558 - accuracy: 0.3333
Epoch 7/200
1/1 [==============================] - 0s 17ms/step - loss: 0.6569 - accuracy: 0.5000
Epoch 8/200
1/1 [==============================] - 0s 18ms/step - loss: 0.6404 - accuracy: 0.3333
Epoch 9/200
1/1 [==============================] - 0s 17ms/step - loss: 0.6409 - accuracy: 0.3333
Epoch 10/200
1/1 [===========